#! /usr/bin/env bash

filename='day1.txt'
part1=0
n=0
while read line || [ -n "$line" ]; do
digit=$(echo $line | tr -d -c 0-9)
first_char="${digit:0:1}"
last_char="${digit:(-1)}"
first=$(expr $first_char \* 10)
total=$(expr $first + $last_char)
part1=$((part1+total))
n=$((n+1))
done < $filename
echo Day 1 Part 1: "${part1}"